#!/bin/bash

# Copyright (c) 2016-2017  Erik Martin-Dorel
# Version: 0.9.2

function is_among() {
    local arg="$1"
    shift
    for elt; do
        if [ "$arg" = "$elt" ]; then
            return 0
        fi
    done
    return 1
}

function get_lock() {
    if mkdir "$lockdir"; then
        echo "$prog: successfully acquired lock" >&2
        trap 'rm -rf "$lockdir"' 0
    else
        echo "$prog: cannot acquire lock on '$lockdir'" >&2
        exit 0
    fi
}

function main() {
    local lockdir="/tmp/${USER}_gnome-screenshot-wrapper"
    local prog='gnome-screenshot'
    local prefix
    prefix="$(xdg-user-dir PICTURES)/"
    local format='%Y-%m-%d_%H-%M-%S'
    local suffix='_Screenshot.png'

    local interactFlags=("-c" "--clipboard" "-i" "--interactive" "--gapplication-service" "-h" "--help" "--help-all" "--help-gtk" "--help-gapplication")
    # --gapplication-service is triggered when clicking on the .desktop icon

    local interact="false"
    local ret='0'
    for arg; do
        if is_among "$arg" "${interactFlags[@]}"; then
            interact="true"
        fi
    done

    if [ "$interact" = "false" ]; then
        get_lock
        tmp=$(mktemp "$lockdir/tmp.XXXXXXXXXX.png")

        /usr/bin/gnome-screenshot -f "$tmp" "$@" || ret="$?"
        if [ "$ret" -ne 0 ]; then
            echo "$prog: an error occured." >&2
            exit "$ret"
        fi

        fil="${prefix}$(date "+$format")${suffix}"
        fil=$(zenity --title="Choose a target file" --file-selection --filename="$fil" --save --confirm-overwrite --file-filter="PNG image files | *.png")

        if [ $? -ne 0 ] || [ "$fil" = "" ]; then
            echo "$prog: action canceled" >&2
            exit 1
        else
            mv -f "$tmp" "$fil"
        fi
        exit "$ret" # explicit quit to run the trap using local var ($lockdir)
    else
        exec /usr/bin/gnome-screenshot "$@"
    fi
}

main "$@"
