#!/bin/bash

# Author: Erik Martin-Dorel, 2016-2017
# Version: 0.8-git
#
# Instructions:
# $ sudo dpkg-divert --add --rename --divert /usr/bin/gnome-screenshot.real /usr/bin/gnome-screenshot
# $ sudo cp -iv gnome-screenshot /usr/bin/gnome-screenshot
# $ sudo chown -v root:root /usr/bin/gnome-screenshot
# $ sudo chmod -v +x /usr/bin/gnome-screenshot

function is_among() {
    local arg="$1"
    shift
    for elt; do
        if [ "$arg" = "$elt" ]; then
            return 0
        fi
    done
    return 1
}

function get_lock() {
    if mkdir "$lockdir"; then
        echo "$prog: successfully acquired lock" >&2
        trap 'rm -rf "$lockdir"' 0
    else
        echo "$prog: cannot acquire lock on '$lockdir'" >&2
        exit 0
    fi
}

function main() {
    local lockdir='/tmp/gnome-screenshot-wrapper'
    local prog='gnome-screenshot'

    local interactFlags=("-c" "--clipboard" "-i" "--interactive" "--gapplication-service" "-h" "--help" "--help-all" "--help-gtk" "--help-gapplication")
    # --gapplication-service is triggered when clicking on the .desktop icon
    local areaFlags=("-a" "--area")

    local interact="false"
    local area="false"
    for arg; do
        if is_among "$arg" "${interactFlags[@]}"; then
            interact="true"
        fi
        if is_among "$arg" "${areaFlags[@]}"; then
            area="true"
        fi
    done

    if [ "$interact" = "false" ]; then
        get_lock
        if [ "$area" = "false" ]; then
            tmp=$(mktemp "$lockdir/tmp.XXXXXXXXXX.png")

            if ! gnome-screenshot.real -f "$tmp" "$@"; then
                echo "$prog: An error occured." >&2
                exit 2
            fi

            fil=$(date -Is)
            fil=${fil%+*}
            fil=${fil//:/-}
            fil=${fil/T/_}
            fil="$HOME/Pictures/${fil}_Screenshot.png"
            fil=$(zenity --title="Choose a target file" --file-selection --filename="$fil" --save --confirm-overwrite --file-filter="PNG image files | *.png")

            if [ $? -ne 0 ] || [ "$fil" = "" ]; then
                echo "$prog: action canceled" >&2
                exit 1
            else
                mv -f "$tmp" "$fil"
            fi
        else
            fil=$(date -Is)
            fil=${fil%+*}
            fil=${fil//:/-}
            fil=${fil/T/_}
            fil="$HOME/Pictures/${fil}_Screenshot.png"
            fil=$(zenity --title="Choose a target file" --file-selection --filename="$fil" --save --confirm-overwrite --file-filter="PNG image files | *.png")

            if [ $? -ne 0 ] || [ "$fil" = "" ]; then
                echo "$prog: action canceled" >&2
                exit 1
            fi
            gnome-screenshot.real -f "$fil" "$@"
        fi
        exit 0 # explicit quit to run the trap w.r.t. the local var ($lockdir)
    else
        exec gnome-screenshot.real "$@"
    fi
}

main "$@"
