#!/bin/bash

# Author: Erik Martin-Dorel, 2016-2017
# Version: 0.8-git
#
# Instructions:
# $ sudo dpkg-divert --add --rename --divert /usr/bin/gnome-screenshot.real /usr/bin/gnome-screenshot
# $ sudo cp -iv gnome-screenshot /usr/bin/gnome-screenshot
# $ sudo chown -v root:root /usr/bin/gnome-screenshot
# $ sudo chmod -v +x /usr/bin/gnome-screenshot

function is_among() {
    local arg="$1"
    shift
    for elt; do
        if [ "$arg" = "$elt" ]; then
            return 0
        fi
    done
    return 1
}

interactFlags=("-c" "--clipboard" "-i" "--interactive" "--gapplication-service" "-h" "--help" "--help-all" "--help-gtk" "--help-gapplication")
# --gapplication-service is triggered when clicking on the .desktop icon
areaFlags=("-a" "--area")

interact="false"
area="false"
for arg; do
    if is_among "$arg" "${interactFlags[@]}"; then
        interact="true"
    fi
    if is_among "$arg" "${areaFlags[@]}"; then
        area="true"
    fi
done

# the following test could be optimized
if ls -1qA /tmp/gnome-screenshot_*.png 2>/dev/null | grep -q .; then
    echo "The existence of the following files suggest gnome-screenshot is running:" >&2
    ls -1qA /tmp/gnome-screenshot_*.png >&2
    exit 2
fi

if [ "$interact" = "false" ]; then
    if [ "$area" = "false" ]; then
        tmp=$(mktemp "/tmp/gnome-screenshot_XXX.png")
        gnome-screenshot.real -f "$tmp" "$@"

        if [ $? -ne 0 -o $(stat -c "%c" "$tmp") -eq 0 ]; then
            echo "An error occured." >&2
            rm -f "$tmp"
            exit 2
        fi

        fil=$(date -Is)
        fil=${fil%+*}
        fil=${fil//:/-}
        fil=${fil/T/_}
        fil="$HOME/Pictures/${fil}_Screenshot.png"
        fil=$(zenity --title="Choose a target file" --file-selection --filename="$fil" --save --confirm-overwrite --file-filter="PNG image files | *.png")

        if [ $? -ne 0 -o "x$fil" = "x" ]; then
            echo "Action canceled." >&2
            rm -f "$tmp"
            exit 1
        else
            mv -f "$tmp" "$fil"
        fi
    else
        # the following "lock" could be optimized
        tmp=$(mktemp "/tmp/gnome-screenshot_XXX.png")

        fil=$(date -Is)
        fil=${fil%+*}
        fil=${fil//:/-}
        fil=${fil/T/_}
        fil="$HOME/Pictures/${fil}_Screenshot.png"
        fil=$(zenity --title="Choose a target file" --file-selection --filename="$fil" --save --confirm-overwrite --file-filter="PNG image files | *.png")

        rm -f "$tmp"
        if [ $? -ne 0 -o "x$fil" = "x" ]; then
            echo "Action canceled." >&2
            exit 1
        fi
        gnome-screenshot.real -f "$fil" "$@"
    fi
else
    gnome-screenshot.real "$@"
fi
